exclude: [bin, CNAME, Gemfile, Gemfile.lock, README.md, slate]
markdown: kramdown
permalink: :title
safe: true
syntax-highlighting:
  enabled: true
kramdown:
  input: GFM
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
gems:
  - jekyll-redirect-from

